{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc27fa35a90>: Failed to establish a new connection: [Errno 111] Connection refused',))","children":[{"name":"正向用例：登录后成功创建订单","uid":"ac574c75ad40d822","parentUid":"9450af94867bec4a7d3c1eb71e3942d1","status":"broken","time":{"start":1758342661300,"stop":1758342661303,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"9450af94867bec4a7d3c1eb71e3942d1"},{"name":"AttributeError: 'str' object has no attribute 'isascii'","children":[{"name":"test_create_order_data_driven[case_data1]","uid":"92dad0a949a7c30f","parentUid":"5bcf0fd580c3226bee575f95076e15fe","status":"broken","time":{"start":1758342661553,"stop":1758342661553,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5bcf0fd580c3226bee575f95076e15fe"},{"name":"Exception: 登录失败: {\n  \"code\": 401,\n  \"msg\": \"用户名或密码错误\"\n}","children":[{"name":"正向用例：登录后成功创建订单","uid":"7d2ab8b9e060e9ae","parentUid":"8fb27587ada131e477fff715b9edd1b0","status":"broken","time":{"start":1758437187628,"stop":1758437187635,"duration":7},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":7,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"8fb27587ada131e477fff715b9edd1b0"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}